# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Marcin Zieba <marcinpsk@gmail.com>

version = 1

[[annotations]]
path = [
    "LICENSE",
    "LICENSES/**",
    "*.egg-info/**",
    "contrib/**",
    "netbox_interface_name_rules/migrations/**",
    ".gitignore",
    ".envrc",
    ".devcontainer/devcontainer.json",
    ".devcontainer/.env.example",
    ".github/copilot-instructions.md",
    ".github/dependabot.yml",
    "CHANGELOG.md",
]
SPDX-FileCopyrightText = "2025 Marcin Zieba <marcinpsk@gmail.com>"
SPDX-License-Identifier = "Apache-2.0"
