# Generated by Django 5.2.10 on 2026-02-21 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_interface_name_rules", "0005_platform"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interfacenamerule",
            options={"ordering": ["module_type__model", "pk"]},
        ),
    ]
