# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Marcin Zieba <marcinpsk@gmail.com>
# Generated by Django 5.2.10 on 2026-02-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_interface_name_rules", "0008_constraint_nonempty_pattern"),
    ]

    operations = [
        migrations.AddField(
            model_name="interfacenamerule",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
