# Generated by Django 5.2.10 on 2026-02-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_interface_name_rules", "0009_interfacenamerule_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="interfacenamerule",
            name="applies_to_device_interfaces",
            field=models.BooleanField(default=False),
        ),
    ]
