# Generated by Django 5.2.10 on 2026-02-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0225_gfk_indexes"),
        ("extras", "0134_owner"),
        ("netbox_interface_name_rules", "0010_interfacenamerule_applies_to_device_interfaces"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="interfacenamerule",
            name="interfacenamerule_module_type_mode_check",
        ),
        migrations.AddConstraint(
            model_name="interfacenamerule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("applies_to_device_interfaces", True), ("module_type__isnull", True)),
                    models.Q(
                        ("applies_to_device_interfaces", False),
                        ("module_type__isnull", True),
                        ("module_type_is_regex", True),
                        ("module_type_pattern__gt", ""),
                    ),
                    models.Q(
                        ("applies_to_device_interfaces", False),
                        ("module_type__isnull", False),
                        ("module_type_is_regex", False),
                    ),
                    _connector="OR",
                ),
                name="interfacenamerule_module_type_mode_check",
            ),
        ),
    ]
