# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Marcin Zieba <marcinpsk@gmail.com>
# Generated by Django 5.2.10 on 2026-02-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "netbox_interface_name_rules",
            "0011_remove_interfacenamerule_interfacenamerule_module_type_mode_check_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="interfacenamerule",
            name="interfacenamerule_unique_exact",
        ),
        migrations.AddConstraint(
            model_name="interfacenamerule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("applies_to_device_interfaces", False), ("module_type_is_regex", False)),
                fields=("module_type", "parent_module_type", "device_type", "platform"),
                name="interfacenamerule_unique_exact",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="interfacenamerule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("applies_to_device_interfaces", True)),
                fields=("module_type_pattern", "device_type", "platform"),
                name="interfacenamerule_unique_device_iface",
                nulls_distinct=False,
            ),
        ),
    ]
