# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Marcin Zieba <marcinpsk@gmail.com>
# Generated by Django 6.0.6 on 2026-07-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_interface_name_rules", "0012_remove_interfacenamerule_interfacenamerule_unique_exact_and_more"),
    ]

    operations = [
        # Existing rules keep producing the flat topology they were written for.
        migrations.AddField(
            model_name="interfacenamerule",
            name="breakout_mode",
            field=models.CharField(default="flat", max_length=20),
        ),
        migrations.AddField(
            model_name="interfacenamerule",
            name="parent_name_template",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
