# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Marcin Zieba <marcinpsk@gmail.com>
"""Compare two automatic naming performance artifacts and write a readable summary.

Usage: python performance/compare.py BEFORE.json AFTER.json OUT.md

SQL statement counts are deterministic for equivalent inputs. PostgreSQL cache metrics depend on
buffer-cache state and concurrent activity. Machine time is only evidence when both runs were taken
on the same hardware under a comparable load. The summary reports the environment for comparison.
"""

import json
import re
import sys
from collections import Counter
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from performance.artifact import DATABASE_METRICS, validate_artifact  # noqa: E402

_TIME_METRICS = (
    ("wall", "median_ms", "Wall median (ms)"),
    ("wall", "p95_ms", "Wall p95 (ms)"),
    ("process_cpu", "median_ms", "CPU median (ms)"),
)

_COMPARISON_INTRO = (
    "Generated by `performance/compare.py` from the before and after artifacts of the "
    "interface-family refactor. SQL statement counts are deterministic for equivalent inputs. "
    "Cache metrics depend on PostgreSQL buffer-cache state and concurrent activity. Machine time "
    "is only evidence when both runs were taken on the same otherwise-idle hardware."
)


def _artifact_path(raw, must_exist):
    """Resolve *raw* inside this repository, refusing a path that points outside it."""
    candidate = Path(raw)
    path = (candidate if candidate.is_absolute() else _ROOT / candidate).resolve()
    if not path.is_relative_to(_ROOT):
        raise SystemExit(f"{raw} is outside the repository")
    if must_exist and not path.is_file():
        raise SystemExit(f"{raw} is not a readable artifact")
    return path


def _statement_table(sql):
    """Return the table a normalized statement reads or writes, for attribution."""
    match = re.search(r'(?:FROM|INTO|UPDATE)\s+"([a-z_]+)"', sql)
    return match.group(1) if match else sql.split()[0][:24]


def _calls_by_table(scenario):
    """Return how many statements the scenario issued against each table."""
    counts: Counter = Counter()
    for entry in scenario["database"]["statements"]:
        counts[_statement_table(entry["normalized_sql"])] += entry["calls"]
    return counts


def _attribution(name, before_scenario, after_scenario):
    """Return the per-table statement deltas behind one scenario's change."""
    before_calls, after_calls = _calls_by_table(before_scenario), _calls_by_table(after_scenario)
    rows = []
    for table in sorted(set(before_calls) | set(after_calls)):
        change = after_calls[table] - before_calls[table]
        if change:
            rows.append(f"| `{name}` | `{table}` | {before_calls[table]} | {after_calls[table]} | {change:+d} |")
    return rows


def _scenarios(artifact):
    """Return the artifact's scenarios keyed by name."""
    return {scenario["name"]: scenario for scenario in artifact["scenarios"]}


def _scenario_names(before, after):
    """Return the scenario-name union in stable artifact order."""
    return (*before, *(name for name in after if name not in before))


def _delta(before, after):
    """Return the absolute and percentage change, or None when there is no baseline to divide by."""
    change = after - before
    if not before:
        return change, None
    return change, change / before * 100


def _format(value):
    """Return a compact fixed-point rendering of one metric value."""
    if isinstance(value, float) and not value.is_integer():
        return f"{value:.2f}"
    return f"{int(value)}"


def _comparison_cells(before, after, before_unavailable, after_unavailable):
    """Return rendered comparison cells for one optional metric."""
    if before is None or after is None:
        before_value = before_unavailable if before is None else _format(before)
        after_value = after_unavailable if after is None else _format(after)
        return before_value, after_value, "n/a", "n/a"
    change, percent = _delta(before, after)
    share = "n/a" if percent is None else f"{percent:+.1f}%"
    return _format(before), _format(after), _format(change), share


def _metric_row(name, label, before, after, before_unavailable, after_unavailable):
    """Render one database-work or machine-time comparison row."""
    before_value, after_value, change, share = _comparison_cells(
        before,
        after,
        before_unavailable,
        after_unavailable,
    )
    return f"| `{name}` | {label} | {before_value} | {after_value} | {change} | {share} |"


def _database_scenario(name, before_scenario, after_scenario):
    """Return metric rows and an optional statement regression for one scenario."""
    before_unavailable = "missing baseline" if before_scenario is None else "n/a"
    after_unavailable = "missing" if after_scenario is None else "n/a"
    rows = []
    regression = None
    for key, label in DATABASE_METRICS:
        old = None if before_scenario is None else before_scenario["database"]["totals"].get(key)
        new = None if after_scenario is None else after_scenario["database"]["totals"].get(key)
        rows.append(_metric_row(name, label, old, new, before_unavailable, after_unavailable))
        if key == "statement_calls" and old is not None and new is not None and new > old:
            regression = (name, label, old, new)
    return rows, regression


def _database_table(before, after):
    """Return the per-scenario database-work comparison."""
    lines = ["| Scenario | Metric | Before | After | Change | Share |", "| --- | --- | ---: | ---: | ---: | ---: |"]
    regressions = []
    for name in _scenario_names(before, after):
        scenario_lines, regression = _database_scenario(name, before.get(name), after.get(name))
        lines.extend(scenario_lines)
        if regression is not None:
            regressions.append(regression)
    return lines, regressions


def _time_value(scenario, section, key):
    """Return one timing value, or None when the scenario was not measured."""
    if scenario is None:
        return None
    machine_time = scenario["machine_time"]
    return None if machine_time is None else machine_time[section][key]


def _time_table(before, after):
    """Return the per-scenario machine-time comparison."""
    lines = ["| Scenario | Metric | Before | After | Change | Share |", "| --- | --- | ---: | ---: | ---: | ---: |"]
    for name in _scenario_names(before, after):
        before_scenario = before.get(name)
        after_scenario = after.get(name)
        before_unavailable = "missing baseline" if before_scenario is None else "not measured"
        after_unavailable = "missing" if after_scenario is None else "not measured"
        for section, key, label in _TIME_METRICS:
            old = _time_value(before_scenario, section, key)
            new = _time_value(after_scenario, section, key)
            lines.append(_metric_row(name, label, old, new, before_unavailable, after_unavailable))
    return lines


def _load_span(artifact):
    """Return the run-queue length a run started and finished under."""
    load = artifact["environment"].get("host_load")
    if not load:
        return "not recorded"
    return f"{load['started']['one_minute']:.2f} to {load['finished']['one_minute']:.2f}"


def _environment_table(before, after):
    """Return the revisions and settings each run was taken under."""
    rows = ["| Field | Before | After |", "| --- | --- | --- |"]
    for key in ("plugin_revision", "netbox_revision", "netbox_version", "cpu_model", "operating_system_release"):
        rows.append(f"| {key} | `{before['environment'].get(key)}` | `{after['environment'].get(key)}` |")
    for key in ("samples", "warmups"):
        rows.append(f"| {key} | `{before['configuration'].get(key)}` | `{after['configuration'].get(key)}` |")
    postgres_before = before["environment"].get("postgresql", {}).get("server_version")
    postgres_after = after["environment"].get("postgresql", {}).get("server_version")
    rows.append(f"| postgresql | `{postgres_before}` | `{postgres_after}` |")
    settings_before = before["environment"].get("postgresql", {}).get("planner_settings")
    settings_after = after["environment"].get("postgresql", {}).get("planner_settings")
    planner_status = "identical" if settings_before == settings_after else "CHANGED"
    rows.append(f"| planner settings | `{planner_status}` | `{planner_status}` |")
    load_before = _load_span(before)
    load_after = _load_span(after)
    rows.append(f"| host load (1 min, start to end) | `{load_before}` | `{load_after}` |")
    return rows


def main(argv):
    """Write the comparison of two artifacts to a Markdown file."""
    if len(argv) != 4:
        raise SystemExit(__doc__)
    before = json.loads(_artifact_path(argv[1], must_exist=True).read_text())
    after = json.loads(_artifact_path(argv[2], must_exist=True).read_text())
    validate_artifact(before, argv[1])
    validate_artifact(after, argv[2])
    destination = _artifact_path(argv[3], must_exist=False)
    before_scenarios, after_scenarios = _scenarios(before), _scenarios(after)

    database_lines, regressions = _database_table(before_scenarios, after_scenarios)
    report = [
        "# Automatic naming performance comparison",
        "",
        _COMPARISON_INTRO,
        "",
        "## Environment",
        "",
        *_environment_table(before, after),
        "",
        "## Database work",
        "",
        *database_lines,
        "",
        "## Machine time",
        "",
        *_time_table(before_scenarios, after_scenarios),
        "",
        "## Statement-count regressions",
        "",
    ]
    if regressions:
        report.extend(f"- `{name}` {label}: {_format(old)} to {_format(new)}" for name, label, old, new in regressions)
        report += [
            "",
            "### Where those statements come from",
            "",
            "Each raised scenario is broken down by the table its statements touch, so the work this "
            "plugin drives can be told apart from the per-save bookkeeping NetBox does for the object "
            "types and custom fields the database happens to hold.",
            "",
            "| Scenario | Table | Before | After | Change |",
            "| --- | --- | ---: | ---: | ---: |",
        ]
        for name, _label, _old, _new in regressions:
            report.extend(_attribution(name, before_scenarios[name], after_scenarios[name]))
    else:
        report.append("None. No scenario issues more statements than the baseline.")
    report.append("")
    destination.write_text("\n".join(report))
    print(f"wrote {destination} ({len(regressions)} statement-count regressions)")


if __name__ == "__main__":
    main(sys.argv)
