# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Marcin Zieba <marcinpsk@gmail.com>
"""Plan and execute interface-family operations."""

from .batch import (
    BatchOutcome,
    ModuleFamilyPlans,
    apply_rule_to_modules,
    execute_family_plan,
    execute_module_families,
    plan_module_families,
)
from .capabilities import supports_channelization
from .conversion import (
    conversion_offered,
    convert_rule_families,
    execute_conversion,
    plan_module_conversions,
    preview_rule_conversions,
)
from .domain import (
    ConversionCandidate,
    ConversionMember,
    ConversionPlan,
    ConversionPreview,
    FamilyOutcome,
    FamilyStatus,
    FamilyTopology,
    FlatCreationPlan,
    InstalledFamilyPlan,
    InstalledFamilyPlanSet,
    InstalledPlanSetOutcome,
    InterfaceSnapshot,
    MemberOutcome,
    MemberRole,
    PlannedChannel,
    PlannedMember,
    PlannedName,
    ProspectiveFamilyPlan,
    ProspectiveFamilyPlanSet,
    ProspectiveMember,
    StructuralFamilyPlan,
)
from .execution import execute_installed_plan, execute_installed_plan_set
from .installed import (
    device_interface_families,
    interfaces_by_module,
    is_channelized_parent,
    plan_device_interface_rename,
    plan_installed_families,
    plan_interface_rename,
)
from .prospective import (
    ProspectiveInterface,
    describe_interfaces,
    describe_module_interfaces,
    describe_template_interfaces,
    plan_prospective_families,
)
from .structural import (
    execute_flat_family,
    execute_structural_family,
    has_flat_expansion,
    install_channelized_family,
    plan_flat_family,
    plan_structural_family,
)
from .targets import channelized_family_names, one_family_per_name_set, template_channel_suffixes
from .template_names import pinned_template_cache, resolved_template_names

__all__ = (
    "BatchOutcome",
    "ConversionCandidate",
    "ConversionMember",
    "ConversionPlan",
    "ConversionPreview",
    "FamilyOutcome",
    "FamilyStatus",
    "FamilyTopology",
    "FlatCreationPlan",
    "InstalledFamilyPlan",
    "InstalledFamilyPlanSet",
    "InstalledPlanSetOutcome",
    "InterfaceSnapshot",
    "MemberOutcome",
    "MemberRole",
    "ModuleFamilyPlans",
    "PlannedChannel",
    "PlannedMember",
    "PlannedName",
    "ProspectiveFamilyPlan",
    "ProspectiveFamilyPlanSet",
    "ProspectiveInterface",
    "ProspectiveMember",
    "StructuralFamilyPlan",
    "apply_rule_to_modules",
    "channelized_family_names",
    "conversion_offered",
    "convert_rule_families",
    "describe_interfaces",
    "describe_module_interfaces",
    "describe_template_interfaces",
    "device_interface_families",
    "execute_conversion",
    "execute_family_plan",
    "execute_flat_family",
    "execute_installed_plan",
    "execute_installed_plan_set",
    "execute_module_families",
    "execute_structural_family",
    "has_flat_expansion",
    "install_channelized_family",
    "interfaces_by_module",
    "is_channelized_parent",
    "one_family_per_name_set",
    "pinned_template_cache",
    "plan_device_interface_rename",
    "plan_flat_family",
    "plan_installed_families",
    "plan_interface_rename",
    "plan_module_conversions",
    "plan_module_families",
    "plan_prospective_families",
    "plan_structural_family",
    "preview_rule_conversions",
    "resolved_template_names",
    "supports_channelization",
    "template_channel_suffixes",
)
